@startuml
'https://plantuml.com/class-diagram

Class HomePage{
main()
start()
}



Class HomePageController{

TextField searchBox
TextField serialNumberText
TextField nameText
TextField valueText
TextField dueDateBox;


addItemToJsonFile()
addItemClicked()
removeItemClicked()
completedItemsClicked()
clearListClicked()
clearListView()
removeList()
incompleteItemsClicked()
removeButtonClicked()
 removeFromJsonFile()
editButtonClicked()
selectItemClicked()
displaySelectedItem()
initialize()
addPreviousItems()
viewButtonClicked()
}

Class AddItem{
 getItem()
 getJsonArray()
 addToFile()
 getDirectory()
}

Class MyListView{
gotoView()
displayItems()
displayAllItmes()
sort()
getSort()
}

Class FileMaker{
loadFile()
parseJSONData()
saveList()
saveSystem()
}
JavaFx.Application <|-- HomePage


HomePage--HomePageController
AddItem--HomePageController
MyListView--HomePageController
FileMaker--HomePageController
@enduml