@startuml
'https://plantuml.com/class-diagram

Class HomePage{
main()
start()
}



Class HomePageController{

TextField searchBox
TextField serialNumberText
TextField nameText
TextField moneyText
Label errorMsg;
TableView<Item> itemTable;
TableColumn<Item, String> serialNumberColumn;
TableColumn<Item, String> nameColumn;
TableColumn<Item, String> moneyColumn;
ObservableList<Item> observableList
List<String> serialNumbersList;
List<Item> itemsList;


addButtonClicked()
formatMoney()
clearTextBoxes()
validateInput()
loadButtonClicked()
removeButtonClicked()
saveButtonClicked()
initialize()
editTable()
serialNumberEditCommitted()
editSerialNumber()
valueEditCommitted()
 editValue()
 nameEditCommitted()
 editName()
}


Class Finder{
search()
searchTable()
}

Class Item{
name
serialNumber
money
getName()
setName()
getSerialNumber()
setSerialNumber()
getMoney()
setMoney()
}

Class FileManager{
List<Item> loadedItems
List<Item> SavedItems
saveFile()
saveAsJSON()
saveAsHTML()
saveAsTSV()
getFileType()
loadFile()
loadHTML()
gethtmlString()
loadTSV()
parseTSVData()
loadJSON()
}
JavaFx.Application <|-- HomePage


Finder--HomePageController
Item--HomePageController
FileManager--HomePageController
HomePageController--HomePage
@enduml